export const SET_SIGN_IN = "SET_SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const SET_SIGN_UP = "SET_SIGN_UP";
export const SIGN_UP_SECCESS = "SIGN_UP_SECCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const SET_AUTHENTICATING = "SET_AUTHENTICATING";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";

export const ADD_POST = "ADD_POST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_POST_DETAIL = "GET_POST_DETAIL";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAIL = "GET_POST_DETAIL_FAIL";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const FILTER_POST = "FILTER_POST";
export const FILTER_POST_SUCCESS = "FILTER_POST_SUCCESS";
export const FILTER_POST_FAIL = "FILTER_POST_FAIL";

export const SET_TEXT_FILTER = "SET_TEXT_FILTER";
export const START_FILTER = "START_FILTER";
export const APPLY_FILTER = "APPLY_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const CLEAR_RECENT_SEARCH = "CLEAR_RECENT_SEARCH";
export const REMOVE_SELECTED_RECENT = "REMOVE_SELECTED_RECENT";
